
version: '3.9'
services:
  api:
    build:
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
    container_name: express-api
    restart: always

  react-ui:
    build:
       dockerfile: front/Dockerfile
    ports:
      - "8080:8080"
    container_name: react-ui
    restart: always